config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  resources :vehicles

  resources :customers

  resources :employees

  resources :positions

 get "/update_price" => "vehicles#update_price"

  root "vehicles#index"

end

app/models/quote.rb
class Quote < ActiveRecord::Base

  belongs_to :customer
  belongs_to :employee
  belongs_to :vehicle

  after_save :update_vehicle





#update the vehicle availability if the quote is sold.
  def update_vehicle
    if self.sold == true
      Vehicle.update(self.vehicle_id, :available => false)

      q = Quote.find(Quote.where("vehicle_id = ? AND sold = ?", self.vehicle_id, false).pluck(:id))
      q.each do |x|
        x.destroy
      end
    end
  end

  #total all quote totals for those quotes that have been marked as sold.
  def self.gross_revenue
    gross_revenue = 0
    Quote.all.each do |q|
      if q.sold?
        gross_revenue += q.total
      end
    end
    gross_revenue
  end

  def self.net_profit
    net_profit = 0
    Quote.all.each do |q|
      if q.sold?
        net_profit += (q.price * 0.10)
      end
    end
    net_profit
  end

  def self.total_sales
    total_sales = 0
    Quote.all.each do |q|
      if q.sold?
        total_sales += q.tax
      end
    end
    total_sales
  end

  def show_sold
    if sold?
      "Yes"
    else
      "No"
    end
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]


  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:customer_id, :vehicle_id, :employee_id, :price, :tax, :total, :sold)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
    <script>
        function update_price() {

            var newPrice = document.getElementById("quote_vehicle_id").value;
            jQuery.ajax({
                url: "/update_price",
                type: "GET",
                data: {"vehicle_id" : newPrice},
                dataType: "html",
                success: function(data) {
                    jQuery("#quote_price").html(data);
                    update_tT();
                }
            });
        }</script>
    <script>
      function update_tT() {

          console.log("update_tt")
          var newPrice = parseFloat(document.getElementById("quote_price").value);
          var newTax = (newPrice * .043);

          console.log(newPrice);
          console.log(newTax);

          document.getElementById("quote_tax").value = newTax;
          document.getElementById("quote_total").value = (newTax + newPrice);
      }
    </script>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.collection_select :customer_id, Customer.all, :id, :name, prompt: true %>
  </div>
  <div class="field">
    <%= f.label :vehicle_id %><br>
    <%= f.collection_select(:vehicle_id, Vehicle.all, :id, :vin, {:prompt => true}, {:onchange => "update_price(this.value)", :onload => "update_price(this.value)"}) %>
  </div>
  <div class="field">
    <%= f.label :employee_id %><br>
    <%= f.collection_select :employee_id, Employee.all, :id, :name, prompt: true %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :tax %><br>
    <%= f.text_field :tax %>
  </div>
  <div class="field">
    <%= f.label :total %><br>
    <%= f.text_field :total %>
  </div>
  <div class="field">
    <%= f.label :sold %><br>
    <%= f.check_box :sold %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

    <div id="versionsDiv">
    </div>

    <br>
    <br>
    <%= render 'finance_table' %>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Star Quotes</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Customer</th>
      <th>Vehicle</th>
      <th>Employee</th>
      <th>Price</th>
      <th>Tax</th>
      <th>Total</th>
      <th>Sold</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.customer.name %></td>
        <td><%= quote.vehicle.model %></td>
        <td><%= quote.employee.name %></td>
        <td><%= number_to_currency(quote.price) %></td>
        <td><%= number_to_currency(quote.tax) %></td>
        <td><%= number_to_currency(quote.total) %></td>
        <td><%= quote.show_sold %></td>
        <td class="btn btn-success"><%= link_to 'Show', quote %></td>
        <td class="btn btn-warning"><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td class="btn btn-danger"><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

<br>
<br>

<h3>Dealership Financial Report</h3>
<table>
  <thead>
  <tr>
    <th>Gross Revenue</th>
    <th>Net Profit</th>
    <th>Sales Tax</th>
  </tr>
  </thead>
  <tbody>
  <%# @quotes.each do |q| %>
  <tr>
    <td><%= number_to_currency(@quotes.gross_revenue) %></td>
    <td><%= number_to_currency(@quotes.net_profit) %></td>
    <td><%= number_to_currency(@quotes.total_sales) %></td>
  </tr>
  <%# end %>
  </tbody>
</table>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @quote.customer.name %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @quote.vehicle.model %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @quote.employee.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@quote.price) %>
</p>

<p>
  <strong>Tax:</strong>
  <%= number_to_currency(@quote.tax) %>
</p>

<p>
  <strong>Total:</strong>
  <%= number_to_currency(@quote.total) %>
</p>

<p>
  <strong>Sold:</strong>
  <%= @quote.show_sold %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>