config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  resources :vehicles

  resources :customers

  resources :employees

  resources :positions

 get "/update_price" => "vehicles#update_price"

  root "vehicles#index"

end

app/models/employee.rb
class Employee < ActiveRecord::Base

  belongs_to :position
  has_many :quotes

  has_many :employees, class_name: "Employee", foreign_key: "manager_id"
  belongs_to :manager, class_name: "Employee"

  def manager_name
    if self.manager.nil?
      'N/A'
    else
      self.manager.name
    end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :phone, :email, :position_id)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_emp_sales.html.erb
<table class="table table-striped table-hover">
  <tr>
    <th>Vin</th>
    <th>Make</th>
    <th>Model</th>
    <th>Total</th>
    <th>Link</th>
  </tr>

  <% @employee.quotes.each do |q| %>
      <tr>
        <td><%= q.vehicle.vin %></td>
        <td><%= q.vehicle.make %></td>
        <td><%= q.vehicle.model %></td>
        <td><%= number_to_currency(q.total) %></td>
        <td><%= link_to 'View', q %></td>
      </tr>
  <% end %>
</table>

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.number_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :position_id %><br>
    <%= f.number_field :position_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sith Employees</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= number_to_phone(employee.phone) %></td>
        <td><%= employee.email %></td>
        <td><%= employee.position.title %></td>
        <td class="btn btn-success"><%= link_to 'Show', employee %></td>
        <td class="btn btn-warning"><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td class="btn btn-danger"><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= number_to_phone(@employee.phone) %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Position:</strong>
  <%= @employee.position.title %>
</p>

<%= render 'emp_sales' %>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>