config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  resources :vehicles

  resources :customers

  resources :employees

  resources :positions

 get "/update_price" => "vehicles#update_price"

  root "vehicles#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>StarWars</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

        <!--<%= link_to 'Customers', customers_path %>-->
        <!--<%= link_to 'Employees', employees_path %>-->
        <!--<%= link_to 'Vehicles', vehicles_path %>-->
        <!--<%= link_to 'Quotes', quotes_path %>-->

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/vehicles">StarWars Dealership</a>
      </div>
      <div>
        <ul class="nav navbar-nav">
          <li><a href="/vehicles">Vehicles</a></li>
          <li><a href="/quotes">Quotes</a></li>
          <li><a href="/customers">Customers</a></li>
          <li><a href="/employees">Employees</a> </li>
        </ul>
      </div>
    </div>
  </nav>
</head>
<body>
<div class="col-sm-6">
<%= yield %>
</div>
<div class="col-sm-6"></div>
</body>
</html>